before_script:
  - "curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly --disable-sudo --yes"

stages:
  - test
  - bench

test_job:
  stage: test
  script:
    - cargo test --features="random"

bench_job:
  stage: bench
  script:
    - cargo bench --features="random"
