[package]
name        = "cbor"
version     = "0.1.0"
authors     = ["Toralf Wittner <tw@dtex.org>"]
license     = "MPL-2.0"
description = "CBOR Codec implementation"
homepage    = "https://github.com/twittner/cbor-codec"
repository  = "git@github.com:twittner/cbor-codec.git"

[dependencies]
byteorder = "> 0.3.0"

[dev-dependencies]
rustc-serialize = "> 0.3.0"
