[package]
name        = "cbor-codec"
version     = "0.1.0"
authors     = ["Toralf Wittner <tw@dtex.org>"]
license     = "MPL-2.0"
description = "CBOR Codec implementation"
homepage    = "https://github.com/twittner/cbor-codec"
repository  = "git@github.com:twittner/cbor-codec.git"
keywords    = ["cbor", "encoding", "binary"]

[lib]
name = "cbor"

[features]
arbitraries = ["quickcheck", "rand"]

[dependencies]
byteorder = "> 0.3.0"

[dependencies.quickcheck]
version  = "> 0.2.0"
optional = true

[dependencies.rand]
version  = "> 0.3.0"
optional = true

[dev-dependencies]
quickcheck        = "> 0.2.0"
quickcheck_macros = "> 0.2.0"
rand              = "> 0.3.0"
rustc-serialize   = "> 0.3.0"

[[test]]
name = "tests"
